

INSERT INTO ENDERECO(CEP, LOGRADOURO, COMPLEMENTO, BAIRRO, LOCALIDADE, UF, UNIDADE, IBGE, GIA)
VALUES('04046-100', 'AVENIDA DAS NAÇÕES UNIDAS', '100', 'VILA JARDINS', 'SÃO PAULO', 'SP', '', '', '');

INSERT INTO ENDERECO(CEP, LOGRADOURO, COMPLEMENTO, BAIRRO, LOCALIDADE, UF, UNIDADE, IBGE, GIA)
VALUES('04046-120', 'JARDINS', '200', 'VILA MATILDE', 'SÃO PAULO', 'SP', '', '', '');

INSERT INTO ENDERECO(CEP, LOGRADOURO, COMPLEMENTO, BAIRRO, LOCALIDADE, UF, UNIDADE, IBGE, GIA)
VALUES('04046-123', 'R. DA CANTAREIRA', '20', 'IPIRANGA', 'SÃO PAULO', 'SP', '', '', '');

INSERT INTO ENDERECO(CEP, LOGRADOURO, COMPLEMENTO, BAIRRO, LOCALIDADE, UF, UNIDADE, IBGE, GIA)
VALUES('04046-123', 'R. DA CANTAREIRA', '201', 'IPIRANGA', 'SÃO PAULO', 'SP', '', '', '');


INSERT INTO CLIENTE(CPF, IDADE, NOME, RG, ENDERECO_ID)
VALUES('123456789', 49, 'FULANO DE TAL', '123412343', 1);

INSERT INTO CLIENTE(CPF, IDADE, NOME, RG, ENDERECO_ID)
VALUES('123333544', 30, 'MARIA ROBERTA ', '123412343', 2);

INSERT INTO CLIENTE(CPF, IDADE, NOME, RG, ENDERECO_ID)
VALUES('123357999', 22, 'CYRO PEREIRA GOMES', '123412343', 3);